### PR TITLE
Add docker container for application

### PR DESCRIPTION
**Pull request by carsongee**
Just a quick add of a docker file and compose/fig file.

### CODE REVIEW

**Comment by pdpinch** [comment]
Is for evaluating alternatives to Heroku for deployment? 

----------------
I am mobile.

**Comment by carsongee** [comment]
yep, plus it is pretty convenient for local dev too

**Comment by bdero** [comment]
Building this now to test it out.

**Comment by bdero** [comment]
Awesome stuff - tested working with docker-compose. :bullettrain_front:

**Pull request merged**
