### PR TITLE
Run via foreman/heroku with uwsgi

### LINKED ISSUE #16: Add heroku/foreman support to project
Add relevant config to run as a foreman/heroku project

### PR DESCRIPTION
**Pull request by carsongee**
closes #16

### CODE REVIEW

**Comment by pdpinch** [comment]
This may be excessive, but do we want to add anything to the readme to help folks prepare for the Deploy to Heroku?

maybe along the lines of:

Deploy to Heroku
=============

Just click the button, and be prepared to log in to Heroku. You will need the [contents of a ``.htpasswd`` file](http://httpd.apache.org/docs/2.2/misc/password_encryptions.html) to configure basic authentication, and a [certificate that will work with MIT's Lmod service](http://pylmod.readthedocs.org/en/master/#getting-started). 

Or maybe it's easier to just add the links to the form? 

Anyway, just a thought.

**Comment by carsongee** [comment]
So, this is kind of a split PR issue, the doc issue that @othercarson helpfully reviewed yesterday has more heroku deployment instructions.  This does look like it is probably worth incorporating there once everything else lands.

**Comment by pdpinch** [comment]
Do we have an app cert I can use for testing, or should I request my own? (I think I'll request my own anyway, but I don't know how long it takes)

**Comment by carsongee** [comment]
You can always just use your personal cert too

**Comment by carsongee** [comment]
Actually, even more importantly, this won't work until #23 lands I think (at least for retrieving grades), the nice form and such should still load, just everything will error out

**Comment by pdpinch** [comment]
Ok. I can confirm that much. =)

Dumb question: what's the certificate string supposed to look like? Will I get a 500 or something more descriptive when that's wrong?

**Comment by carsongee** [comment]
I tried to be descriptive in the app.json, but it is the contents of your SSL cert and key, i.e.
```
-----BEGIN CERTIFICATE-----
...
...
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
...
...
-----END RSA PRIVATE KEY-----
```
It lets you know that it is wrong by nothing working and logging a stack trace, but probably nothing user friendly since this doesn't actually have/need a real interface other than the logs

**Comment by bdero** [comment]
This looks good to me. :shaved_ice: Any follow up on this @pdpinch ?

**Comment by bdero** [comment]
Also, there are conflicts from the last few merges.

**Comment by pdpinch** [comment]
I haven't tested this end-to-end yet, but I'm satisfied by what I've seen other do. :+1:

**Comment by carsongee** [comment]
silly .gitignore conflict.  This is rebased

**Comment by bdero** [comment]
Excellent. :on:

**Pull request merged**
