### PR TITLE
Add configuration

### PR DESCRIPTION
**Pull request by carsongee**
This should address #8 and is required for almost everything else.

### CODE REVIEW

**Comment by carsongee** [comment]
As a developer side note, it is ridiculously difficult to test module level globals, so doing configuration by module level globals (ala `flask.config.by_object`) while nice to use, i.e. `config.<item>` probably not worth the trouble, and going forward I think I'll configure by returning a dictionary or something like I did in  https://github.com/mitodl/gitreload/blob/master/gitreload/config.py instead of how we are doing it in orcoursetrion and our flask sample app.

**Comment by pwilkins** [comment]
running setup tests returns this error:
``` 
Searching for pylmod
Reading https://pypi.python.org/simple/pylmod/
Couldn't find index page for 'pylmod' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pylmod
error: Could not find suitable distribution for Requirement.parse('pylmod')
```
I assume this is not an actual error, but an artifact of not finding pylmod in pypi.

**Comment by carsongee** [comment]
To run locally you need to do `pip install -r requirements.txt` and then `python setup.py test` should work fine.

**Comment by carsongee** [comment]
It would be resolved by us having a release of pylmod in the cheese shop

**Pull request merged**
