### PR TITLE
updated Heroku key for travis

### PR DESCRIPTION
**Pull request by pdpinch**
attempting to address https://travis-ci.org/mitodl/lmod_proxy/builds/97895518#L808-L809 but I won't know until it's merged into master. 

@bdero

### CODE REVIEW

**Comment by bdero** [comment]
Let's give it a shot @pdpinch . :+1:

**Comment by pdpinch** [comment]
No dice. Same error:

```
body: "{\"id\":\"forbidden\",\"error\":\"You do not have access to the app lmod-proxy-ci.\"}" (does the app 'lmod-proxy-ci' exist and does your account have access to it?)

 <>failed to deploy


```

I think I had found an issue on the travis repo that seemed relevant. Let me try to find that.

**Comment by pdpinch** [comment]
Hmm. I'm noticing that Travis is authenticating as me (pdpinch@mit.edu <mailto:pdpinch@mit.edu>) and I don't have any privileges on the app. 

I probably should have made the key with a different account. I'll give that a shot.

**Comment by bdero** [comment]
Ah, will you use mitx-devops@mit.edu?

**Comment by pdpinch** [comment]
Yeah, in https://github.com/mitodl/lmod_proxy/pull/41

**Pull request merged**
